url: reesdraminski.com
baseurl: ""
title: "Rees Draminski"
author: "Rees Draminski"
description: "Where I blog about my various interests and things that I am working on."
permalink: /:categories/:title/
timezone: "America/New_York"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap